### PR TITLE
Async Mode Updates

### PR DESCRIPTION
**Pull request by a-barrera**

### CODE REVIEW

**Comment by rlippert** [comment]
I tried to test this change out, and just with these XML changes but no other changes I get an endless XSCOM error loop in step 7.2 after mss_volt runs:

 25.76132|FAPI|p9_mss_volt.C: End mss volt
 25.76134|ISTEPS_TRACE|call_mss_volt exit
 25.89682|XSCOM|E>XSCOM status error HMER: 00c0020000000000 ,XSComStatus = 2, Addr=50040018
 25.89686|XSCOM|collectXscomFFDC: XSCOM COLLECT FFDC STARTED
 25.89710|XSCOM|resetScomEngine: XSCOM RESET INTIATED
 25.89733|ERRL|>>addHwCallout(0x00050000 0x6 0x2 0x0)
 25.89734|TARG|[TARG] E> Number of Parent chip is not 1, but 0
 25.89735|ERRL|>>addProcedureCallout(0x55, 0x5)
 25.89739|SCOM|Ignoring error 90000008 because it is a multicast scom with a PIB_CHIPLET_OFFLINE error, and this is expected
 25.92170|PRDF|>>PRDF::main() Global attnType=0002
 25.94600|PRDF|>>PRDF::noLock_initialize()
 25.99477|PRDF|>>PlatConfigurator::build()
 26.07798|IPMI|dd: I>read b2h ok 14:30 seq d len 0 cc 0
 26.07868|IPMI|dd: I>write ok 10:30 seq e len a
 26.28677|IPMI|dd: I>read b2h ok 14:30 seq e len 0 cc 0
 26.28681|IPMI|dd: I>write ok 10:30 seq f len a
 26.47249|IPMI|dd: I>read b2h ok 14:30 seq f len 0 cc 0
 26.47423|IPMI|dd: I>write ok 10:30 seq 10 len a
 26.67824|IPMI|dd: I>read b2h ok 14:30 seq 10 len 0 cc 0
 26.67829|IPMI|dd: I>write ok 10:30 seq 11 len a
 26.87609|IPMI|dd: I>read b2h ok 14:30 seq 11 len 0 cc 0
 26.87614|IPMI|dd: I>write ok 10:30 seq 12 len a
 27.08007|IPMI|dd: I>read b2h ok 14:30 seq 12 len 0 cc 0
 27.08067|IPMI|dd: I>write ok 10:30 seq 13 len a
 27.29151|IPMI|dd: I>read b2h ok 14:30 seq 13 len 0 cc 0
 27.29198|IPMI|dd: I>write ok 10:30 seq 14 len a
 27.43483|PRDF|E>[addDomainChips] getFunctionalTargetList() returned empty list for i_type=40
 27.48099|IPMI|dd: I>read b2h ok 14:30 seq 14 len 0 cc 0
 27.48189|IPMI|dd: I>write ok 10:30 seq 15 len a
 27.51495|PRDF|<<PlatConfigurator::build()
 27.51496|PRDF|<<PRDF::noLock_initialize()
 27.63555|PRDF|I>PRD Signature 00000000 00000000
 27.63561|PRDF|I>PRD Signature 00050000 00000000
 27.65983|XSCOM|E>XSCOM status error HMER: 00c0020000000000 ,XSComStatus = 2, Addr=50040018
 27.65986|XSCOM|collectXscomFFDC: XSCOM COLLECT FFDC STARTED
 27.66011|XSCOM|resetScomEngine: XSCOM RESET INTIATED
 27.66035|ERRL|>>addHwCallout(0x00050000 0x6 0x2 0x0)
 27.66036|TARG|[TARG] E> Number of Parent chip is not 1, but 0
 27.66038|ERRL|>>addProcedureCallout(0x55, 0x5)
 27.66041|SCOM|Ignoring error 9000000A because it is a multicast scom with a PIB_CHIPLET_OFFLINE error, and this is expected
 27.66047|XSCOM|E>XSCOM status error HMER: 00c0020000000000 ,XSComStatus = 2, Addr=50040009
 27.66051|XSCOM|collectXscomFFDC: XSCOM COLLECT FFDC STARTED
 27.66073|XSCOM|resetScomEngine: XSCOM RESET INTIATED
 27.66093|ERRL|>>addHwCallout(0x00050000 0x6 0x2 0x0)
 27.66094|TARG|[TARG] E> Number of Parent chip is not 1, but 0
 27.66096|ERRL|>>addProcedureCallout(0x55, 0x5)
 27.66099|SCOM|Ignoring error 9000000B because it is a multicast scom with a PIB_CHIPLET_OFFLINE error, and this is expected
 27.66317|PRDF|I>PRD Signature 00050000 C77E0000
 27.66321|PRDF|I>PRD Signature 00050000 C77E0010
 27.66324|PRDF|I>PRD Signature 00050000 C77E0010
 27.68209|IPMI|dd: I>read b2h ok 14:30 seq 15 len 0 cc 0
 27.68267|IPMI|dd: I>write ok 10:30 seq 16 len a
 27.71258|PRDF|I>PRD Signature 00230000 00000000
 27.71325|PRDF|I>PRD Signature 00230000 493E0000
 27.71331|PRDF|I>PRD Signature 00230000 493E0004
 27.71333|PRDF|I>PRD Signature 00230000 493E0004
 27.71337|PRDF|I>PRD Signature 00060000 00000000
 27.71389|PRDF|I>PRD Signature 00060000 7EF00000
 27.71427|PRDF|I>PRD Signature 00060000 7EF00002
 27.71429|PRDF|I>PRD Signature 00060000 7EF00002
 27.71450|PRDF|I>PRD Signature 00060000 F08D0000
 27.71458|PRDF|I>PRD Signature 00060000 F08D000D
 27.73896|PRDF|I>PRD Signature 00060000 F08D000D
 27.79215|ERRL|>>addHwCallout(0x00060000 0x6 0x0 0x0)
 27.79364|ERRL|commitErrLog() called by E500 for eid=90000009, Reasoncode=E504
 27.79365|ERRL|>>ErrlManager::sendErrlogToMessageQueue
 27.79366|ERRL|I>Send an error log to message queue to commit. eid=90000009
 27.79367|ERRL|<<ErrlManager::sendErrlogToMessageQueue
 27.79368|ERRL|I>Got an error log Msg - Type: 0x00000030
 27.79370|PRDF|I>[ErrDataService::GenerateSrcPfa] PRD called to analyze an error: 0x00060000 0xf08d000d
 27.79377|PRDF|<<PRDF::main()
 27.79888|XSCOM|E>XSCOM status error HMER: 00c0020000000000 ,XSComStatus = 2, Addr=50040018
 27.79891|XSCOM|collectXscomFFDC: XSCOM COLLECT FFDC STARTED
 27.79918|XSCOM|resetScomEngine: XSCOM RESET INTIATED

**Comment by a-barrera** [comment]
Still missing some fixes in master-next for async mode support. Right now we are running with the following patch: 
https://github.com/sannerd/op-build/blob/p9_bu_17_02_27.canidate_2/openpower/package/hostboot/p9Patches/hostboot-1002-Defer-setup-of-MC-multicast-groups-in-async-mode.patch

**Comment by sannerd** [comment]
You also need the SBE updates from p9_bu_17_02_27.canidate_2.  Specifically you _have_ to have the SBE on the system prior to doing the customization.  If you need to recover the SBE you can add this temp patch to Hostboot to get back to the point of re customization (or just allow it to run):

diff --git a/src/usr/initservice/istepdispatcher/istepdispatcher.C b/src/usr/initservice/istepdispatcher/istepdispatcher.C
index a963b58..adfc851 100644
--- a/src/usr/initservice/istepdispatcher/istepdispatcher.C
+++ b/src/usr/initservice/istepdispatcher/istepdispatcher.C
@@ -758,6 +758,7 @@ errlHndl_t IStepDispatcher::doIstep(uint32_t i_istep,
         else if ((true == theStep->taskflags.check_attn) &&
                  (false == iv_mpiplMode))
         {
+#if 0
             TRACDCOMP(g_trac_initsvc,
                       INFO_MRK"Check for attentions and invoke PRD" );

@@ -768,6 +769,7 @@ errlHndl_t IStepDispatcher::doIstep(uint32_t i_istep,
                 TRACFCOMP( g_trac_initsvc, ERR_MRK"doIstep: error from "
                           "checkForIplAttentions");
             }
+#endif
         }

 #ifdef CONFIG_RECONFIG_LOOP_TESTS_ENABLE

**Comment by a-barrera** [comment]
@rlippert please check this again with a new build from master-next.

**Pull request merged**
